model_params:
  name: VanillaAE
  latent_dim: 128

exp_params:
  dataset: celeba
  data_path: data
  img_size: 64
  batch_size: 144
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  max_epochs: 50

logging_params:
  save_dir: logs/
  name: VanillaAE
  manual_seed: 1265
