model_params:
  name: VDVAE
  embedding_dim: 256
  num_embeddings: 512
  img_size: 64
  beta: 1.0

exp_params:
  dataset: celeba
  data_path: data
  img_size: 64
  batch_size: 128 # Better to have a square number
  LR: 0.0002
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: [2]
  max_epochs: 30

logging_params:
  save_dir: logs/
  name: VDVAE
  manual_seed: 1265
